apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  name: {{ .Values.redis.service.name }}
  labels:
    app: mym
    component: {{ .Values.redis.service.name }}
spec:
  type: ClusterIP
  selector:
    app: mym
    component: {{ .Values.redis.service.name }}
  ports:
    - name: redis
      port: 6379
      targetPort: redis